
spring:
  application:
    name: microservico-usuarios

  datasource:
    url: jdbc:mysql://localhost:3306/microservico_usuario_db
    username: root
    password: sasa
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: ${PORT:0}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
